version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: ranciid-amp_app_1
      APP_PORT: 8080

  app:
    image: mitchtalmadge/amp-dockerized:latest
    restart: unless-stopped
    environment:
      TZ: America/Los_Angeles
      UID: "1000"
      GID: "1000"
      PORT: "8080"
      IPBINDING: "0.0.0.0"
      USERNAME: "admin"
      PASSWORD: "ChangeInCompose!1"
      AMP_AUTO_UPDATE: "true"
    volumes:
      - ${APP_DATA_DIR}/amp:/home/amp
    networks:
      default:
        mac_address: "02:42:AC:60:20:92"
